# Generated by Django 3.1 on 2020-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200908_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contact_me_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
