# Generated by Django 3.1 on 2020-09-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20200904_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='isTraditional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chief',
            name='award_types',
            field=models.CharField(default=' ', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='chief',
            name='chief_img',
            field=models.ImageField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='food',
            name='F_img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
