# Generated by Django 3.1 on 2020-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20200904_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='chief',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
