# Generated by Django 3.1 on 2020-09-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_chief_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='promot',
            field=models.BooleanField(default=False),
        ),
    ]
