# Generated by Django 3.1 on 2020-09-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_food_promot'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
